version: '3.7'
services:
  nuxt:
    tty: true
    stdin_open: true
    init: true
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/tmp
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NUXT_HOST: 0.0.0.0
    command: ['yarn', 'dev']
