version: '3.7'
services:
  nuxt:
    tty: true
    stdin_open: true
    init: true
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../docker/nuxt:/app/.nuxt
      - ../docker/entrypoint.sh:/app/entrypoint.sh
      - ../:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: ['dev']
